export const ERROR_CODES = {
  AUTH_400_INVALID_PAYLOAD: "AUTH_400_INVALID_PAYLOAD",
  AUTH_401_TOKEN_INVALID: "AUTH_401_TOKEN_INVALID",
  AUTH_401_CREDENTIALS_INVALID: "AUTH_401_CREDENTIALS_INVALID",
  AUTH_409_ACCOUNT_EXISTS: "AUTH_409_ACCOUNT_EXISTS",
  RELATION_400_INVITE_CODE_INVALID: "RELATION_400_INVITE_CODE_INVALID",
  RELATION_404_NOT_BOUND: "RELATION_404_NOT_BOUND",
  RELATION_409_ALREADY_BOUND: "RELATION_409_ALREADY_BOUND",
  RELATION_409_SELF_BIND_FORBIDDEN: "RELATION_409_SELF_BIND_FORBIDDEN",
  RELATION_410_INVITE_CODE_EXPIRED: "RELATION_410_INVITE_CODE_EXPIRED",
  CHAT_400_INVALID_CONTENT: "CHAT_400_INVALID_CONTENT",
  CHAT_400_INVALID_MESSAGE_IDS: "CHAT_400_INVALID_MESSAGE_IDS"
} as const;

export type ApiErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
